name: Build Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r Face_Landmarker/requirements.txt
        pyinstaller Face_Landmarker/Face_Landmarker_Link.spec
    - name: 'Zip files'
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'Face_Landmarker_Link_linux.zip'
        path: dist/Face_Landmarker_Link
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build_artifact_linux
        path: Face_Landmarker_Link_linux.zip

  build_windows:

      runs-on: windows-latest

      steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r Face_Landmarker/requirements.txt
          pyinstaller Face_Landmarker/Face_Landmarker_Link.spec
      - name: 'Zip files'
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'Face_Landmarker_Link_windows.zip'
          path: dist/Face_Landmarker_Link
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build_artifact_windows
          path: Face_Landmarker_Link_windows.zip

  build_macos:

      runs-on: macos-latest

      steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r Face_Landmarker/requirements.txt
          pyinstaller Face_Landmarker/Face_Landmarker_Link.spec
      - name: 'Zip files'
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'Face_Landmarker_Link_macos.zip'
          path: dist/Face_Landmarker_Link
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build_artifact_macos
          path: Face_Landmarker_Link_macos.zip
